### ISSUE TITLE
Sapper Support

### ISSUE THREAD

**Issue by rienkkk** [AlexxNB/mdi-svelte#2]
How would I be able to intergrate this with Sapper instead of Svelte?

**Comment by AlexxNB** [comment]
What the problem doing it? Svelte is a part of the Sapper, so just use mdi-svelte as usual.

**Comment by rienkkk** [comment]
I tought it had to do with the fact that I am using Sapper but I get the following error after following the installation instructions:

```
Error: Cannot find module '@mdi/js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/rienk/projects/website/projecth/__sapper__/dev/server/server.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by rienkkk** [comment]
Made a stupid mistake and tought this was the issue - case closed my mistake :)!
